// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Configurações padrão das variáveis de ambiente
const DEFAULT_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Cache das configurações
let configCache: { url?: string; key?: string } | null = null;
let dynamicClient: any = null;

// Cliente inicial para buscar configurações (usando configurações padrão)
const initialClient = createClient(DEFAULT_SUPABASE_URL, DEFAULT_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Função para buscar configurações do banco
async function getConfig() {
  if (configCache) return configCache;
  
  try {
    const { data } = await initialClient
      .from('configuracoes')
      .select('chave, valor')
      .in('chave', ['supabase.url', 'supabase.anon_key']);
    
    if (data && data.length > 0) {
      const config: { url?: string; key?: string } = {};
      data.forEach((item) => {
        if (item.chave === 'supabase.url' && item.valor) {
          config.url = item.valor;
        }
        if (item.chave === 'supabase.anon_key' && item.valor) {
          config.key = item.valor;
        }
      });
      
      // Só usa configuração personalizada se ambas existirem
      if (config.url && config.key) {
        configCache = config;
        return config;
      }
    }
  } catch (error) {
    console.log('Usando configurações padrão');
  }
  
  // Fallback para configurações padrão
  configCache = { url: DEFAULT_SUPABASE_URL, key: DEFAULT_SUPABASE_PUBLISHABLE_KEY };
  return configCache;
}

// Função para obter o cliente dinâmico
async function getDynamicClient() {
  if (dynamicClient) return dynamicClient;
  
  const config = await getConfig();
  
  // Se as configurações são diferentes das padrão, criar novo cliente
  if (config.url !== DEFAULT_SUPABASE_URL || config.key !== DEFAULT_SUPABASE_PUBLISHABLE_KEY) {
    dynamicClient = createClient(config.url!, config.key!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } else {
    // Usar cliente inicial se configurações são padrão
    dynamicClient = initialClient;
  }
  
  return dynamicClient;
}

// Exportar cliente - inicialmente usa o padrão, mas pode ser atualizado
export let supabase = initialClient;

// Função para inicializar o cliente com configurações dinâmicas
export const initializeSupabaseClient = async () => {
  try {
    const client = await getDynamicClient();
    // @ts-ignore - Substituindo a referência do cliente
    supabase = client;
    return client;
  } catch (error) {
    console.log('Erro ao inicializar cliente dinâmico, usando padrão');
    return initialClient;
  }
};

// Função para resetar o cache (útil quando configurações são atualizadas)
export const resetSupabaseConfig = () => {
  configCache = null;
  dynamicClient = null;
  // Reinicializar cliente
  initializeSupabaseClient();
};