// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Configurações padrão das variáveis de ambiente
const DEFAULT_SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Cliente inicial para buscar configurações
const initialClient = createClient(DEFAULT_SUPABASE_URL, DEFAULT_SUPABASE_PUBLISHABLE_KEY);

// Cache das configurações
let configCache: { url?: string; key?: string } | null = null;
let dynamicClient: any = null;

// Função para buscar configurações do banco
async function getConfig() {
  if (configCache) return configCache;
  
  try {
    const { data } = await initialClient
      .from('configuracoes')
      .select('chave, valor')
      .in('chave', ['supabase.url', 'supabase.anon_key']);
    
    if (data && data.length > 0) {
      const config: { url?: string; key?: string } = {};
      data.forEach((item) => {
        if (item.chave === 'supabase.url' && item.valor) {
          config.url = item.valor;
        }
        if (item.chave === 'supabase.anon_key' && item.valor) {
          config.key = item.valor;
        }
      });
      
      // Só usa configuração personalizada se ambas existirem
      if (config.url && config.key) {
        configCache = config;
        return config;
      }
    }
  } catch (error) {
    console.log('Usando configurações padrão');
  }
  
  // Fallback para configurações padrão
  configCache = { url: DEFAULT_SUPABASE_URL, key: DEFAULT_SUPABASE_PUBLISHABLE_KEY };
  return configCache;
}

// Função para obter o cliente dinâmico
async function getDynamicClient() {
  if (dynamicClient) return dynamicClient;
  
  const config = await getConfig();
  
  dynamicClient = createClient(config.url!, config.key!, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
  
  return dynamicClient;
}

// Proxy para o cliente Supabase que usa configurações dinâmicas
export const supabase = new Proxy({} as any, {
  get(target, prop) {
    if (typeof prop === 'string') {
      return async (...args: any[]) => {
        const client = await getDynamicClient();
        const method = client[prop];
        if (typeof method === 'function') {
          return method.apply(client, args);
        }
        return method;
      };
    }
    return undefined;
  }
});

// Função para resetar o cache (útil quando configurações são atualizadas)
export const resetSupabaseConfig = () => {
  configCache = null;
  dynamicClient = null;
};